# WorkflowNo_6
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2.0-dev2
class: Workflow

label: WorkflowNo_6
doc: A workflow including the tool(s) XTandem, mzRecal, Comet, PeptideProphet, ProteinProphet.

inputs:
  input1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
outputs:
  output1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: ProteinProphet5/ProteinProphet_out_1
steps:
  XTandem1:
    in:
      XTandem_in_1: input1
      XTandem_in_2: input2
    out: [XTandem_out_1, XTandem_out_2]
    run:
      class: Operation
      inputs:
        XTandem_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        XTandem_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        XTandem_out_1:
          type: File
          format: "http://edamontology.org/format_3247" # mzIdentML
      hints:
        SoftWareRequirement:
          packages:
            XTandem: ["http://edamontology.org/xtandem1"]
      intent: ["http://edamontology.org/operation_3631", "http://edamontology.org/operation_3646", "http://edamontology.org/operation_3645", "http://edamontology.org/operation_3767", "http://edamontology.org/operation_3647"]
  mzRecal2:
    in:
      mzRecal_in_1: input1
      mzRecal_in_2: XTandem1/XTandem_out_1
    out: [mzRecal_out_1, mzRecal_out_2]
    run:
      class: Operation
      inputs:
        mzRecal_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        mzRecal_in_2:
          type: File
          format: "http://edamontology.org/format_3247" # mzIdentML
      outputs:
        mzRecal_out_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
      hints:
        SoftWareRequirement:
          packages:
            mzRecal: ["http://edamontology.org/mzrecal1"]
      intent: ["http://edamontology.org/operation_3627"]
  Comet3:
    in:
      Comet_in_1: mzRecal2/mzRecal_out_1
      Comet_in_2: input2
    out: [Comet_out_1, Comet_out_2]
    run:
      class: Operation
      inputs:
        Comet_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        Comet_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        Comet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            Comet: ["http://edamontology.org/comet1"]
      intent: ["http://edamontology.org/operation_3646"]
  PeptideProphet4:
    in:
      PeptideProphet_in_1: Comet3/Comet_out_1
    out: [PeptideProphet_out_1, PeptideProphet_out_2]
    run:
      class: Operation
      inputs:
        PeptideProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        PeptideProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            PeptideProphet: ["http://edamontology.org/peptideprophet1"]
      intent: ["http://edamontology.org/operation_3664", "http://edamontology.org/operation_3675", "http://edamontology.org/operation_3631", "http://edamontology.org/operation_3649"]
  ProteinProphet5:
    in:
      ProteinProphet_in_1: PeptideProphet4/PeptideProphet_out_1
    out: [ProteinProphet_out_1, ProteinProphet_out_2]
    run:
      class: Operation
      inputs:
        ProteinProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        ProteinProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3747" # protXML
      hints:
        SoftWareRequirement:
          packages:
            ProteinProphet: ["http://edamontology.org/proteinprophet1"]
      intent: ["http://edamontology.org/operation_3695", "http://edamontology.org/operation_3664", "http://edamontology.org/operation_3644", "http://edamontology.org/operation_3767"]
