# WorkflowNo_17
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_17
doc: A workflow including the tool(s) Comet, idconvert, mzRecal, Comet, PeptideProphet, ProteinProphet.

inputs:
  input1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  Comet1:
    run:  ../../tools/Comet/Comet.cwl
    in:
      Comet_in_1: input1
      Comet_in_2: input2
    out: [Comet_out_1]
  idconvert2:
  # Manual edit: ../../tools/idconvert/idconvert.cwl -> ../../tools/idconvert/idconvert_to_mzIdentML.cwl
    run: ../../tools/idconvert/idconvert_to_mzIdentML.cwl
    in:
      idconvert_in_1: Comet1/Comet_out_1
    out: [idconvert_out_1]
  mzRecal3:
    run: ../../tools/mzRecal/mzRecal.cwl
    in:
      mzRecal_in_1: input1
      mzRecal_in_2: idconvert2/idconvert_out_1
    out: [mzRecal_out_1]
  Comet4:
    run: ../../tools/Comet/Comet.cwl
    in:
      Comet_in_1: mzRecal3/mzRecal_out_1
      Comet_in_2: input2
    out: [Comet_out_1]
  PeptideProphet5:
    run: ../../tools/PeptideProphet/PeptideProphet.cwl
    in:
      PeptideProphet_in_1: Comet4/Comet_out_1
       # Manual edit: PeptideProphet_in_2: mzRecal3/mzRecal_out_1
      PeptideProphet_in_2:  mzRecal3/mzRecal_out_1
      # Manual edit: PeptideProphet_in_3: input2
      PeptideProphet_in_3: input2

    out: [PeptideProphet_out_1]
  ProteinProphet6:
    run: ../../tools/ProteinProphet/ProteinProphet.cwl
    in:
      ProteinProphet_in_1: PeptideProphet5/PeptideProphet_out_1
      # Manual edit: ProteinProphet_in_2: input2
      ProteinProphet_in_2: input2
    out: [ProteinProphet_out_1]
outputs:
  output1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    #format: "http://edamontology.org/format_3244" # mzML
    outputSource: mzRecal3/mzRecal_out_1
