# WorkflowNo_20
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2.0-dev2
class: Workflow

label: WorkflowNo_20
doc: A workflow including the tool(s) Comet, idconvert, mzRecal, Comet, PeptideProphet, ProteinProphet, protXml2IdList, GOEnrichment.

inputs:
  input1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input3:
    type: File
    format: "http://edamontology.org/format_2196_plain" # OBO format_p
  input4:
    type: File
    format: "http://edamontology.org/format_3475_plain" # TSV_p
outputs:
  output1:
    type: File
    format: "http://edamontology.org/format_2330_plain" # Textual format_p
    outputSource: GOEnrichment8/GOEnrichment_out_1
steps:
  Comet1:
    in:
      Comet_in_1: input1
      Comet_in_2: input2
    out: [Comet_out_1, Comet_out_2, Comet_out_3, Comet_out_4]
    run:
      class: Operation
      inputs:
        Comet_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        Comet_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        Comet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            Comet: ["http://edamontology.org/comet1"]
      intent: ["http://edamontology.org/operation_3646"]
  idconvert2:
    in:
      idconvert_in_1: Comet1/Comet_out_1
    out: [idconvert_out_1, idconvert_out_2, idconvert_out_3, idconvert_out_4]
    run:
      class: Operation
      inputs:
        idconvert_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        idconvert_out_1:
          type: File
          format: "http://edamontology.org/format_3247" # mzIdentML
      hints:
        SoftWareRequirement:
          packages:
            idconvert: ["http://edamontology.org/idconvert1"]
      intent: ["http://edamontology.org/operation_1812", "http://edamontology.org/operation_3434", "http://edamontology.org/operation_0335"]
  mzRecal3:
    in:
      mzRecal_in_1: input1
      mzRecal_in_2: idconvert2/idconvert_out_1
    out: [mzRecal_out_1, mzRecal_out_2, mzRecal_out_3, mzRecal_out_4]
    run:
      class: Operation
      inputs:
        mzRecal_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        mzRecal_in_2:
          type: File
          format: "http://edamontology.org/format_3247" # mzIdentML
      outputs:
        mzRecal_out_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
      hints:
        SoftWareRequirement:
          packages:
            mzRecal: ["http://edamontology.org/mzrecal1"]
      intent: ["http://edamontology.org/operation_3627"]
  Comet4:
    in:
      Comet_in_1: mzRecal3/mzRecal_out_1
      Comet_in_2: input2
    out: [Comet_out_1, Comet_out_2, Comet_out_3, Comet_out_4]
    run:
      class: Operation
      inputs:
        Comet_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        Comet_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        Comet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            Comet: ["http://edamontology.org/comet1"]
      intent: ["http://edamontology.org/operation_3646"]
  PeptideProphet5:
    in:
      PeptideProphet_in_1: Comet4/Comet_out_1
    out: [PeptideProphet_out_1, PeptideProphet_out_2, PeptideProphet_out_3, PeptideProphet_out_4]
    run:
      class: Operation
      inputs:
        PeptideProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        PeptideProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            PeptideProphet: ["http://edamontology.org/peptideprophet1"]
      intent: ["http://edamontology.org/operation_3664", "http://edamontology.org/operation_3675", "http://edamontology.org/operation_3631", "http://edamontology.org/operation_3649"]
  ProteinProphet6:
    in:
      ProteinProphet_in_1: PeptideProphet5/PeptideProphet_out_1
    out: [ProteinProphet_out_1, ProteinProphet_out_2, ProteinProphet_out_3, ProteinProphet_out_4]
    run:
      class: Operation
      inputs:
        ProteinProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        ProteinProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3747" # protXML
      hints:
        SoftWareRequirement:
          packages:
            ProteinProphet: ["http://edamontology.org/proteinprophet1"]
      intent: ["http://edamontology.org/operation_3695", "http://edamontology.org/operation_3664", "http://edamontology.org/operation_3644", "http://edamontology.org/operation_3767"]
  protXml2IdList7:
    in:
      protXml2IdList_in_1: ProteinProphet6/ProteinProphet_out_1
    out: [protXml2IdList_out_1, protXml2IdList_out_2, protXml2IdList_out_3, protXml2IdList_out_4]
    run:
      class: Operation
      inputs:
        protXml2IdList_in_1:
          type: File
          format: "http://edamontology.org/format_3747" # protXML
      outputs:
        protXml2IdList_out_1:
          type: File
          format: "http://edamontology.org/format_2330_plain" # Textual format_p
      hints:
        SoftWareRequirement:
          packages:
            protXml2IdList: ["http://edamontology.org/protXml2IdList"]
      intent: ["http://edamontology.org/operation_3434", "http://edamontology.org/operation_0335"]
  GOEnrichment8:
    in:
      GOEnrichment_in_1: protXml2IdList7/protXml2IdList_out_1
      GOEnrichment_in_2: input3
      GOEnrichment_in_3: input4
    out: [GOEnrichment_out_1, GOEnrichment_out_2, GOEnrichment_out_3, GOEnrichment_out_4]
    run:
      class: Operation
      inputs:
        GOEnrichment_in_1:
          type: File
          format: "http://edamontology.org/format_2330_plain" # Textual format_p
        GOEnrichment_in_2:
          type: File
          format: "http://edamontology.org/format_2196_plain" # OBO format_p
        GOEnrichment_in_3:
          type: File
          format: "http://edamontology.org/format_3475_plain" # TSV_p
      outputs:
        GOEnrichment_out_1:
          type: File
          format: "http://edamontology.org/format_2330_plain" # Textual format_p
      hints:
        SoftWareRequirement:
          packages:
            GOEnrichment: ["http://edamontology.org/goenrichment1"]
      intent: ["http://edamontology.org/operation_2436"]
