# WorkflowNo_11
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2.0-dev2
class: Workflow

label: WorkflowNo_11
doc: A workflow including the tool(s) Comet, PeptideProphet, ProteinProphet, protXml2IdList.

inputs:
  input1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
outputs:
  output1:
    type: File
    format: "http://edamontology.org/format_2330_plain" # Textual format_p
    outputSource: protXml2IdList4/protXml2IdList_out_1
steps:
  Comet1:
    in:
      Comet_in_1: input1
      Comet_in_2: input2
    out: [Comet_out_1, Comet_out_2]
    run:
      class: Operation
      inputs:
        Comet_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        Comet_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        Comet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            Comet: ["http://edamontology.org/comet1"]
      intent: ["http://edamontology.org/operation_3646"]
  PeptideProphet2:
    in:
      PeptideProphet_in_1: Comet1/Comet_out_1
    out: [PeptideProphet_out_1, PeptideProphet_out_2]
    run:
      class: Operation
      inputs:
        PeptideProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        PeptideProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            PeptideProphet: ["http://edamontology.org/peptideprophet1"]
      intent: ["http://edamontology.org/operation_3664", "http://edamontology.org/operation_3675", "http://edamontology.org/operation_3631", "http://edamontology.org/operation_3649"]
  ProteinProphet3:
    in:
      ProteinProphet_in_1: PeptideProphet2/PeptideProphet_out_1
    out: [ProteinProphet_out_1, ProteinProphet_out_2]
    run:
      class: Operation
      inputs:
        ProteinProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        ProteinProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3747" # protXML
      hints:
        SoftWareRequirement:
          packages:
            ProteinProphet: ["http://edamontology.org/proteinprophet1"]
      intent: ["http://edamontology.org/operation_3695", "http://edamontology.org/operation_3664", "http://edamontology.org/operation_3644", "http://edamontology.org/operation_3767"]
  protXml2IdList4:
    in:
      protXml2IdList_in_1: ProteinProphet3/ProteinProphet_out_1
    out: [protXml2IdList_out_1, protXml2IdList_out_2]
    run:
      class: Operation
      inputs:
        protXml2IdList_in_1:
          type: File
          format: "http://edamontology.org/format_3747" # protXML
      outputs:
        protXml2IdList_out_1:
          type: File
          format: "http://edamontology.org/format_2330_plain" # Textual format_p
      hints:
        SoftWareRequirement:
          packages:
            protXml2IdList: ["http://edamontology.org/protXml2IdList"]
      intent: ["http://edamontology.org/operation_3434", "http://edamontology.org/operation_0335"]
