# WorkflowNo_17
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2.0-dev2
class: Workflow

label: WorkflowNo_17
doc: A workflow including the tool(s) Comet, idconvert, mzRecal, Comet, PeptideProphet, ProteinProphet.

inputs:
  input1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
outputs:
  output1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: ProteinProphet6/ProteinProphet_out_1
steps:
  Comet1:
    in:
      Comet_in_1: input1
      Comet_in_2: input2
    out: [Comet_out_1, Comet_out_2]
    run:
      class: Operation
      inputs:
        Comet_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        Comet_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        Comet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            Comet: ["http://edamontology.org/comet1"]
      intent: ["http://edamontology.org/operation_3646"]
  idconvert2:
    in:
      idconvert_in_1: Comet1/Comet_out_1
    out: [idconvert_out_1, idconvert_out_2]
    run:
      class: Operation
      inputs:
        idconvert_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        idconvert_out_1:
          type: File
          format: "http://edamontology.org/format_3247" # mzIdentML
      hints:
        SoftWareRequirement:
          packages:
            idconvert: ["http://edamontology.org/idconvert1"]
      intent: ["http://edamontology.org/operation_1812", "http://edamontology.org/operation_3434", "http://edamontology.org/operation_0335"]
  mzRecal3:
    in:
      mzRecal_in_1: input1
      mzRecal_in_2: idconvert2/idconvert_out_1
    out: [mzRecal_out_1, mzRecal_out_2]
    run:
      class: Operation
      inputs:
        mzRecal_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        mzRecal_in_2:
          type: File
          format: "http://edamontology.org/format_3247" # mzIdentML
      outputs:
        mzRecal_out_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
      hints:
        SoftWareRequirement:
          packages:
            mzRecal: ["http://edamontology.org/mzrecal1"]
      intent: ["http://edamontology.org/operation_3627"]
  Comet4:
    in:
      Comet_in_1: mzRecal3/mzRecal_out_1
      Comet_in_2: input2
    out: [Comet_out_1, Comet_out_2]
    run:
      class: Operation
      inputs:
        Comet_in_1:
          type: File
          format: "http://edamontology.org/format_3244" # mzML
        Comet_in_2:
          type: File
          format: "http://edamontology.org/format_1929" # FASTA
      outputs:
        Comet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            Comet: ["http://edamontology.org/comet1"]
      intent: ["http://edamontology.org/operation_3646"]
  PeptideProphet5:
    in:
      PeptideProphet_in_1: Comet4/Comet_out_1
    out: [PeptideProphet_out_1, PeptideProphet_out_2]
    run:
      class: Operation
      inputs:
        PeptideProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        PeptideProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      hints:
        SoftWareRequirement:
          packages:
            PeptideProphet: ["http://edamontology.org/peptideprophet1"]
      intent: ["http://edamontology.org/operation_3664", "http://edamontology.org/operation_3675", "http://edamontology.org/operation_3631", "http://edamontology.org/operation_3649"]
  ProteinProphet6:
    in:
      ProteinProphet_in_1: PeptideProphet5/PeptideProphet_out_1
    out: [ProteinProphet_out_1, ProteinProphet_out_2]
    run:
      class: Operation
      inputs:
        ProteinProphet_in_1:
          type: File
          format: "http://edamontology.org/format_3655" # pepXML
      outputs:
        ProteinProphet_out_1:
          type: File
          format: "http://edamontology.org/format_3747" # protXML
      hints:
        SoftWareRequirement:
          packages:
            ProteinProphet: ["http://edamontology.org/proteinprophet1"]
      intent: ["http://edamontology.org/operation_3695", "http://edamontology.org/operation_3664", "http://edamontology.org/operation_3644", "http://edamontology.org/operation_3767"]
